set(_CATKIN_CURRENT_PACKAGE "labs")
set(labs_VERSION "0.0.0")
set(labs_MAINTAINER "odroid <odroid@todo.todo>")
set(labs_PACKAGE_FORMAT "2")
set(labs_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(labs_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(labs_BUILDTOOL_DEPENDS "catkin")
set(labs_BUILDTOOL_EXPORT_DEPENDS )
set(labs_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(labs_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(labs_TEST_DEPENDS )
set(labs_DOC_DEPENDS )
set(labs_DEPRECATED "")